before_script: rvm get head
language: objective-c                   #Used for Swift or Objective-c
osx_image: xcode8
xcodebuild -project Friend Finder/Friend-Finder.xcodeproj -scheme Friend-Finder -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' build test
