# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Friend-Finder' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Friend-Finder
  # Facebook Pods Dependency
  pod 'Bolts'

  # Facebook SDK Pods
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  target 'Friend-FinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Friend-FinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
